import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import * as fs from "fs";
import * as path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const copyCSS = () => {
	fs.copyFileSync(path.join("src", "obhc-styles.css"), path.join("styles.css"));
	console.log("Copied styles.css to plugin root");
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	define: {
		"global.IS_DEV": JSON.stringify(!prod),
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		{
			name: "css-copy",
			setup(build) {
				build.onEnd(() => {
					copyCSS();
				});
			},
		},
	],
});

// copy CSS on initial build
copyCSS();

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
